# Generated by Django 3.0.1 on 2020-01-30 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='service',
            new_name='services',
        ),
    ]
